name: chesterfly
favicon: null
layout_spectrum: 0.2664933428168297
typography_spectrum: 0.665872604586184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5838714374694973
  lightness: 0.22053926740773022
  saturation: 0.41169891599565744
  rhythmicContrast: 0.9645830404479057
purpose: []
